In [2]:
import os, pathlib
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model
import statsmodels.api as sm


In [3]:
data = pd.read_csv('/home/ruidong/Desktop/An_Introd_to-SL_with_r_and_py/data/Advertising.csv')

In [6]:
data.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [10]:
y = np.array(data['sales'])

In [18]:
x = np.array(data['TV'])

In [38]:
X = np.expand_dims(x, axis=1)

In [ ]:
X_ext = np.insert(X, 0, 1, axis=1)

# Compute Simple Linear Model using statsmodels

In [51]:
model = sm.OLS(y, X_ext)

In [52]:
res = model.fit()

In [53]:
res.params

array([7.03259355, 0.04753664])

In [54]:
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Tue, 03 May 2022   Prob (F-statistic):           1.47e-42
Time:                        17:08:43   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.0326      0.458     15.360      0.0

# Compute Simple Linear Model using sklearn

In [91]:
X_multiple = np.array(data[['TV', 'radio', 'newspaper']])

In [92]:
X_multiple.shape

(200, 3)

In [95]:
X_multiple_ext = np.insert(X_multiple, 0, 1, axis=1)

In [96]:
reg = linear_model.LinearRegression()
reg.fit(X, y)

LinearRegression()

In [97]:
reg.coef_

array([0.04753664])

In [98]:
reg.intercept_

7.032593549127695

# Compute Multiple Linear Model using statsmodels

In [99]:
model_multiple = sm.OLS(y, X_multiple_ext)

In [100]:
res = model_multiple.fit()

In [101]:
res.params

const    2.938889
x1       0.045765
x2       0.188530
x3      -0.001037
dtype: float64

In [104]:
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Tue, 03 May 2022   Prob (F-statistic):           1.58e-96
Time:                        17:48:52   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.0

# Compute Multiple Linear Model using sklearn

In [62]:
y = data['sales']

In [63]:
reg_multiple = linear_model.LinearRegression()
reg_multiple.fit(X_multiple, y)

LinearRegression()

In [64]:
reg_multiple.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [65]:
reg_multiple.intercept_

2.938889369459412